### ISSUE TITLE
Station-bounced radios bluescreen on frequency change

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#14424]
**Issue Description**:
The Ui of SBR's breaks when you change the frequency

**What did you expect to happen**: 
for frequency to change

**What happened instead**:
You get the bluescreen/tgui error screen with this message:

TypeError: Unable to get property 'name' of undefined or null reference
   at Anonymous function (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:5:232033)
   at Anonymous function (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:1:12088)
   at map (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:1:114366)
   at t.Radio (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:5:229847)
   at Anonymous function (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:1:176279)
   at Me (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:1:176042)
   at je (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:1:180191)
   at Anonymous function (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:1:175974)
   at Me (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:1:175709)
   at Re (http://127.0.0.1:51407/tmp24008/tgui.bundle.js:1:180540)

**Why is this bad/What are the consequences**:
Can't change radio frequency

**Steps to reproduce the problem**:
print a SBR, try and change the frequency

**When did the problem start happening**:
Probably somtimes after the radio tgui stuff got in.

**Extra information**:

**Comment by TDSSS** [comment]
@Kyep
