### ISSUE TITLE
TGUI error, power console above secure storage

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14773]
**Issue Description**:

![image](https://user-images.githubusercontent.com/52090703/97504576-86392400-194d-11eb-896a-93c8b71367fd.png)

**Extra information**:

Power issues accross station, but also hotwireing and APC shocking crew

**Comment by moxian** [comment]
Still an issue:

```
TypeError: Object doesn't support property or method 'replace'
   at i (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:83415)
   at Anonymous function (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:204580)
   at Anonymous function (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:204550)
   at Se (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:204528)
   at Ae (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:205664)
   at Anonymous function (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:204858)
   at Se (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:204726)
   at Anonymous function (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:204550)
   at Se (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:204528)
   at Te (http://127.0.0.1:51155/tmp6740/tgui.bundle.js:1:205469)
```
which would be https://github.com/ParadiseSS13/Paradise/blob/df1f548198cf68868ecdef04ca1898c881ff3683/tgui/packages/tgui/components/Icon.js#L15

Again, lights being out, likely due to power overload, though hard to say if it's cause or effect.

**Comment by dearmochi** [comment]
Identified the root cause of this issue. Removing the cell from an APC that is connected to the power monitor sets its `CellStatus` (to pass to TGUI) to `M`, but there is no case for that value when rendering the icon:

https://github.com/ParadiseSS13/Paradise/blob/8f72d7556e769e27f60e6a7f86ed224ab36b7170/tgui/packages/tgui/interfaces/PowerMonitor.js#L252-L263

Fix PR coming soon
