### ISSUE TITLE
NTOS BSOD when using PDA power monitor

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#14886]
**Issue Description**:
Sometimes when you try and open the engineering PDA's power monitor console, it bluescreens with an NTOS error.
You can reset the PDA to use its other functions, but trying to open the power menu again causes the same issue.

**What did you expect to happen**: 
It should display the power monitor console without issue.

**What happened instead**:
NTOS BSOD screen, unable to open any power monitor related functions.

**Steps to reproduce the problem**:
Be engineer or put engineer module into PDA -> Open PDA -> Click on Power Monitor option -> Click on any of the listed consoles -> blue screen

**When did the problem start happening**:
Occurs randomly since I started playing

**Extra information**:
  ███╗   ██╗████████╗ ██████╗ ███████╗
  ████╗  ██║╚══██╔══╝██╔═══██╗██╔════╝
  ██╔██╗ ██║   ██║   ██║   ██║███████╗
  ██║╚██╗██║   ██║   ██║   ██║╚════██║
  ██║ ╚████║   ██║   ╚██████╔╝███████║
  ╚═╝  ╚═══╝   ╚═╝    ╚═════╝ ╚══════╝
 
 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: https://github.com/ParadiseSS13/Paradise. Thank you for your cooperation. 
 TypeError: Unable to get property 'supply' of undefined or null reference
   at h (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:126406)
   at Anonymous function (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:202840)
   at Anonymous function (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:202810)
   at Se (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:202788)
   at Ee (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:203924)
   at Te (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:203763)
   at Se (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:202652)
   at Anonymous function (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:202810)
   at Se (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:202788)
   at Anonymous function (http://127.0.0.1:50305/tmp14248/tgui.bundle.js:1:202810)
 
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)

**Comment by S34NW** [comment]
This does not occur consistently, further testing needed to understand what's happening mid-round to cause this

**Comment by AffectedArc07** [comment]
Same as the regular power monitor bug. Somewhere supply gets nulled out or missing which causes this.
