### ISSUE TITLE
Exosuit Fabricator Error

### ISSUE THREAD

**Issue by TemperanceTempy** [ParadiseSS13/Paradise#16954]
**Issue Description**:

Error with Exosuit Fabricator

**What did you expect to happen**: 

Usual UI load

**What happened instead**:

Fatal error involving the filter

**Why is this bad/What are the consequences**:

Cannot use the exosuit fabricator

**Steps to reproduce the problem**:

I was in the middle of producing a durand when the next time the UI loaded this occurred.

**When did the problem start happening**:

see reproduction steps

**Extra information**:

error log
cooperation. 
 TypeError: Unable to get property 'filter' of undefined or null reference
   at m (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:5:243332)
   at Anonymous function (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:204832)
   at Anonymous function (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:204802)
   at Se (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:204780)
   at Te (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:205721)
   at Se (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:204644)
   at Anonymous function (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:204802)
   at Se (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:204780)
   at Anonymous function (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:204802)
   at Se (http://127.0.0.1:59500/tmp2164/tgui.bundle.js:1:204780)

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)

**Comment by KerbalCitizen** [comment]
UIs don't load properly quite often. The easiest fix is in the special verbs tab -> reload UI resources. Not sure if it would fix this specific error, but worth trying out if it ever happens to you again.

**Comment by Adrer** [comment]
Can confirm this issue happening (UI bluescreen happening on interacting with exosuit fab), only way to resolve was reconstructing the machine, cause unknown.

**Comment by S34NW** [comment]
When this happens, all of RND breaks too.
